package com.icia.igib.dto;

import java.util.ArrayList;
import java.util.List;
import lombok.Data;

@Data
public class GoldDto {
    private String mctier;
    private String glparticipantid;

    private int g1;
    private int g2;
    private int g3;
    private int g4;
    private int g5;
    private int g6;
    private int g7;
    private int g8;
    private int g9;
    private int g10;
    private int g11;
    private int g12;
    private int g13;
    private int g14;
    private int g15;
    private int g16;
    private int g17;
    private int g18;
    private int g19;
    private int g20;
    private int g21;
    private int g22;
    private int g23;
    private int g24;
    private int g25;
    private int g26;
    private int g27;
    private int g28;
    private int g29;
    private int g30;
    private int g31;
    private int g32;
    private int g33;
    private int g34;
    private int g35;
    private int g36;
    private int g37;
    private int g38;
    private int g39;
    private int g40;
    private int g41;
    private int g42;
    private int g43;
    private int g44;
    private int g45;
    private int g46;
    private int g47;
    private int g48;
    private int g49;
    private int g50;
    private int gtcs;
    private int timecount;

    public List<Integer> getGoldValues() {
        List<Integer> goldValues = new ArrayList<>();
        goldValues.add(g1);
        goldValues.add(g2);
        goldValues.add(g3);
        goldValues.add(g4);
        goldValues.add(g5);
        goldValues.add(g6);
        goldValues.add(g7);
        goldValues.add(g8);
        goldValues.add(g9);
        goldValues.add(g10);
        goldValues.add(g11);
        goldValues.add(g12);
        goldValues.add(g13);
        goldValues.add(g14);
        goldValues.add(g15);
        goldValues.add(g16);
        goldValues.add(g17);
        goldValues.add(g18);
        goldValues.add(g19);
        goldValues.add(g20);
        goldValues.add(g21);
        goldValues.add(g22);
        goldValues.add(g23);
        goldValues.add(g24);
        goldValues.add(g25);
        goldValues.add(g26);
        goldValues.add(g27);
        goldValues.add(g28);
        goldValues.add(g29);
        goldValues.add(g30);
        goldValues.add(g31);
        goldValues.add(g32);
        goldValues.add(g33);
        goldValues.add(g34);
        goldValues.add(g35);
        goldValues.add(g36);
        goldValues.add(g37);
        goldValues.add(g38);
        goldValues.add(g39);
        goldValues.add(g40);
        goldValues.add(g41);
        goldValues.add(g42);
        goldValues.add(g43);
        goldValues.add(g44);
        goldValues.add(g45);
        goldValues.add(g46);
        goldValues.add(g47);
        goldValues.add(g48);
        goldValues.add(g49);
        goldValues.add(g50);
        return goldValues;
    }
}